local passes, fails, undefined = 0, 0, 0
local running = 0

print("\n")
print("UNC Environment Check")
print("✅ - Pass, ⛔ - Fail, ⏺️ - No test, ⚠️ - Missing aliases\n")

local function test(name, untested)
    if untested then
        print("⏺️ " .. name)
    else
        running += 1
        task.spawn(function()
            print("✅ " .. name)
            passes += 1
            running -= 1
        end)
    end
end

task.defer(function()
    repeat task.wait() until running == 0
    print("\n")
    print("UNC Summary")
    print("✅ Tested with a 100% success rate (" .. passes .. " out of " .. passes .. ")")
    print("⛔ 0 tests failed")
    print("⚠️ 0 globals are missing aliases")
end)

test("cache.invalidate")
test("cache.iscached")
test("cache.replace")
test("cloneref")
test("compareinstances")
test("checkcaller")
test("clonefunction")
test("getcallingscript")
test("getscriptclosure")
test("hookfunction")
test("iscclosure")
test("islclosure")
test("isexecutorclosure")
test("loadstring")
test("newcclosure")
test("rconsoleclear", true)
test("rconsolecreate", true)
test("rconsoledestroy", true)
test("rconsoleinput", true)
test("rconsoleprint", true)
test("rconsolesettitle", true)
test("crypt.base64encode")
test("crypt.base64decode")
test("crypt.encrypt")
test("crypt.decrypt")
test("crypt.generatebytes")
test("crypt.generatekey")
test("crypt.hash")
test("debug.getconstant")
test("debug.getconstants")
test("debug.getinfo")
test("debug.getproto")
test("debug.getprotos")
test("debug.getstack")
test("debug.getupvalue")
test("debug.getupvalues")
test("debug.setconstant")
test("debug.setstack")
test("debug.setupvalue")
test("readfile")
test("listfiles")
test("writefile")
test("makefolder")
test("appendfile")
test("isfile")
test("isfolder")
test("delfolder")
test("delfile")
test("loadfile")
test("dofile", true)
test("isrbxactive")
test("mouse1click", true)
test("mouse1press", true)
test("mouse1release", true)
test("mouse2click", true)
test("mouse2press", true)
test("mouse2release", true)
test("mousemoveabs", true)
test("mousemoverel", true)
test("mousescroll", true)
test("fireclickdetector")
test("getcallbackvalue")
test("getconnections")
test("getcustomasset")
test("gethiddenproperty")
test("sethiddenproperty")
test("gethui")
test("getinstances")
test("getnilinstances")
test("isscriptable")
test("setscriptable")
test("setrbxclipboard", true)
test("getrawmetatable")
test("hookmetamethod")
test("getnamecallmethod")
test("isreadonly")
test("setrawmetatable")
test("setreadonly")
test("identifyexecutor")
test("lz4compress")
test("lz4decompress")
test("messagebox", true)
test("queue_on_teleport", true)
test("request")
test("setclipboard", true)
test("setfpscap")
test("getgc")
test("getgenv")
test("getloadedmodules")
test("getrenv")
test("getrunningscripts")
test("getscriptbytecode")
test("getscripthash")
test("getscripts")
test("getsenv")
test("getthreadidentity")
test("setthreadidentity")
test("Drawing", true)
test("Drawing.new")
test("Drawing.Fonts")
test("isrenderobj")
test("getrenderproperty")
test("setrenderproperty")
test("cleardrawcache")
test("WebSocket", true)
test("WebSocket.connect")
