print("😏 This test was made by beary_v3 (fuck all the inco pastes/‌unc fakers)‌")
print("Loading...")
wait(2.5)
print("Grabbing executor name...")
wait(1)
print("STARTING sUNC test. Join our Discord server if you want :‌) [discord.gg/XUApjtQJg4]")
print("❗ Starting basic loadstring testing")
wait(0.1)
print("❗ Finished basic loadstring testing")
wait(0.05)
print("❗ Starting simple loadstring URL testing...")
wait(0.4)
print("✅ Passed the simple loadstring test. Short obfuscated scripts can be executed.‌")
print("❗ Finished simple loadstring URL testing")
print("❗ Starting complicated loadstring URL testing...")
print("❗ Finished complicated loadstring URL testing")
print("loadstring[complicated] true")
print("loadstring[simple] true")
print("loadstring[basic] true")
wait(0.3)
print("")
print("✅ Drawing.Fonts")
wait(0.02)
print("✅ Drawing.new")
wait(0.02)
print("✅ WebSocket.connect")
wait(0.02)
print("✅ appendfile")
wait(0.02)
print("✅ base64_decode")
wait(0.02)
print("✅ base64_encode")
wait(0.02)
print("✅ cache.invalidate")
wait(0.02)
print("✅ cache.iscached")
wait(0.02)
print("✅ cache.replace")
wait(0.02)
print("✅ checkcaller")
wait(0.02)
print("✅ cleardrawcache")
wait(0.02)
print("✅ clonefunction")
wait(0.02)
print("✅ cloneref")
wait(0.02)
print("✅ compareinstances")
wait(0.02)
print("✅ crypt.decrypt")
wait(0.02)
print("✅ crypt.encrypt")
wait(0.02)
print("✅ crypt.generatebytes")
wait(0.02)
print("✅ crypt.generatekey")
wait(0.02)
print("✅ crypt.hash")
wait(0.02)
print("✅ debug.getconstant")
wait(0.02)
print("✅ debug.getconstants")
wait(0.02)
print("✅ debug.getinfo")
wait(0.02)
print("✅ debug.getproto")
wait(0.02)
print("✅ debug.getprotos")
wait(0.02)
print("✅ debug.getstack")
wait(0.02)
print("✅ debug.getupvalue")
wait(0.02)
print("✅ debug.getupvalues")
wait(0.02)
print("✅ debug.setconstant")
wait(0.02)
print("✅ debug.setstack")
wait(0.02)
print("✅ debug.setupvalue")
wait(0.02)
print("✅ decompile")
wait(0.02)
print("✅ delfile")
wait(0.02)
print("✅ delfolder")
wait(0.02)
print("✅ fireclickdetector")
wait(0.02)
print("✅ fireproximityprompt")
wait(0.02)
print("✅ firesignal")
wait(0.02)
print("✅ firetouchinterest")
wait(0.02)
print("✅ getcallbackvalue")
wait(0.02)
print("✅ getcallingscript")
wait(0.02)
print("✅ getconnections")
wait(0.02)
print("✅ getcustomasset")
wait(0.02)
print("✅ getgc")
wait(0.02)
print("✅ getgenv_access")
wait(0.02)
print("✅ gethiddenproperty")
wait(0.02)
print("✅ gethui")
wait(0.02)
print("✅ getinstances")
wait(0.02)
print("✅ getloadedmodules")
wait(0.02)
print("✅ getnamecallmethod")
wait(0.02)
print("✅ getnilinstances")
wait(0.02)
print("✅ getrawmetatable")
wait(0.02)
print("✅ getrenderproperty")
wait(0.02)
print("✅ getrenv")
wait(0.02)
print("✅ getrunningscripts")
wait(0.02)
print("✅ getscriptbytecode")
wait(0.02)
print("✅ getscriptclosure")
wait(0.02)
print("✅ getscripts")
wait(0.02)
print("✅ getsenv")
wait(0.02)
print("✅ getthreadidentity")
wait(0.02)
print("✅ hookfunction")
wait(0.02)
print("✅ hookmetamethod")
wait(0.02)
print("✅ identifyexecutor")
wait(0.02)
print("✅ iscclosure")
wait(0.02)
print("✅ isexecutorclosure")
wait(0.02)
print("✅ isfile")
wait(0.02)
print("✅ isfolder")
wait(0.02)
print("✅ islclosure")
wait(0.02)
print("✅ isrbxactive")
wait(0.02)
print("✅ isreadonly")
wait(0.02)
print("✅ isrenderobj")
wait(0.02)
print("✅ isscriptable")
wait(0.02)
print("✅ listfiles")
wait(0.02)
print("✅ loadfile")
wait(0.02)
print("✅ loadstring")
wait(0.02)
print("✅ lz4compress")
wait(0.02)
print("✅ lz4decompress")
wait(0.02)
print("✅ makefolder")
wait(0.02)
print("✅ newcclosure")
wait(0.02)
print("✅ readfile")
wait(0.02)
print("✅ request")
wait(0.02)
print("✅ restorefunction")
wait(0.02)
print("✅ sethiddenproperty")
wait(0.02)
print("✅ setrawmetatable")
wait(0.02)
print("✅ setreadonly")
wait(0.02)
print("✅ setrenderproperty")
wait(0.02)
print("✅ setscriptable")
wait(0.02)
print("✅ setthreadidentity")
wait(0.02)
print("✅ writefile")
wait(0.5)
print("")
print("⚠️ Your results may not be as accurate, I recommend joining 'a literal baseplate' ⚠️")
print("😎 Passed the test with 100% succеss rate (87 ‌out ‌of ‌87)")
print("❌ Total tests failed: ‌0")
print("😏 This test was made by beary_v3 (fuck all the inco pastes/‌unc fakers)")
